#############################################################
# Configuration for the Backup-service.                     #
#############################################################
# It defines what should be backup-ed and when that backup  #
# should take place. There is no incremental backup support #
# by now, please keep that in mind.                         #
#############################################################
delete_after: 7             # keep your backups for 7 days.
target: c:\Backups\DCSSB  # The target directory of your backups. Should be on a cloud / external drive.
backups:
  bot:  # the bot configuration and customizations like reports
    directories:
    - config
    - reports
    schedule:
      days: YYYYYYY           # Mo Di Mi Do Fr Sa So
      times:
      - '00:00'               # You can create multiple times per day, but not a different time on multiple days.
  servers:  # all your DCS servers
    directories:              # Specify which directories you want to backup. They will be zipped.
    - Config
    - Scripts
    - Mods\services\Perun\lua
    - Mods\services\BufferingSocket\lua
    schedule:
      days: YYYYYYY
      times:
      - '00:00'
